sudo: false
language: python
python: 2.7
cache: pip

env:
    - TOX_ENV=py27-django18
    - TOX_ENV=py27-django19
    - TOX_ENV=py27-django110
    - TOX_ENV=py27-django111
    - TOX_ENV=py27-django20
    - TOX_ENV=py33-django18
    - TOX_ENV=py34-django19
    - TOX_ENV=py34-django110
    - TOX_ENV=py34-django111
    - TOX_ENV=py34-django20
    - TOX_ENV=py35-django19
    - TOX_ENV=py35-django110
    - TOX_ENV=py35-django111
    - TOX_ENV=py35-django20
    - TOX_ENV=py36-django19
    - TOX_ENV=py36-django110
    - TOX_ENV=py36-django111
    - TOX_ENV=py36-django20
    - TOX_ENV=pypy-django18
    - TOX_ENV=pypy-django19
    - TOX_ENV=pypy-django110
    - TOX_ENV=pypy-django111
    - TOX_ENV=pypy-django20

install:
    - pip install -r requirements.txt
    - pip install -r requirements_test.txt
    - pip install -e .
    - pip install tox
    - pip install coveralls

script:
    - tox -e $TOX_ENV
    - py.test

after_success:
    - coveralls

notifications:
  email:
    on_success: never
    on_failure: change

